apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-app
  labels:
    app: finance-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: finance-app
  template:
    metadata:
      labels:
        app: finance-app
    spec:
      containers:
      - name: finance-app
        image: <YOUR_DOCKER_IMAGE_NAME>:<YOUR_DOCKER_IMAGE_TAG>
        ports:
        - containerPort: 80
