apiVersion: v1
kind: Service
metadata:
  name: finance-app
  labels:
    app: finance-app
spec:
  type: LoadBalancer
  selector:
    app: finance-app
  ports:
  - name: http
    port: 80
    targetPort: 80
